[project]
name = 'Blockchain-Based-Agricultural-Supply-Chain'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.crop-certification]
path = 'contracts/crop-certification.clar'
clarity_version = 2
epoch = 2.5

[contracts.farm-verification]
path = 'contracts/farm-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.logistics-tracking]
path = 'contracts/logistics-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.quality-verification]
path = 'contracts/quality-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
